### ISSUE TITLE
Adicionar as variáveis de ambiente para o arquivo ENV

### ISSUE THREAD

**Issue by filipebraida** [LeSales/moodle-discord-bot#1]
Uma padronização é utilizar os arquivos .env e .env.example.

Teria que adicionar também no gitignore o arquivo .env.

**Comment by filipebraida** [comment]
O tempo de atualização poderia ser uma constante do env.

**Comment by LeSales** [comment]
`.env` e `.env.example` criados. 

`.env ` adicionado ao `.gitignore`

Variáveis de ambiente criadas para o token do bot e tempo de atualização.
