### ISSUE TITLE
Generalização das URLS

### ISSUE THREAD

**Issue by filipebraida** [LeSales/moodle-discord-bot#2]
A url está fixa. Poderia existir um arquivo com as urls e os nomes dela. 

Exemplo:
`[ { url: "http...", name: "moodle"}, { url: "http...", name: "sigaa"}]`

Teria que ver se o arquivo .json seria a melhor forma de fazer isso.

**Comment by LeSales** [comment]
Criado um novo arquivo `url.js` para armazenar as urls.
